#!/bin/bash

for color in $(cat scss/list.txt); do
	if [ -f scss/colors/$color.scss ]; then
		echo $color
		sass --style=expanded --sourcemap=none scss/colors/$color.scss css/colors/$color.css &&
		:
	fi
done
