#!/bin/bash -e

#  Note:  this script is designed to be run from the fluidity root directory: i.e.:  scss/bootstrap/sassme

for file in alerts badges breadcrumbs buttons button-groups carousel close component-animations components code core dropdowns forms glyphicons grid input-groups javascript jumbotron labels list-group media modals navbar navs normalize pager pagination panels popovers print progress-bars resets responsive-embed responsive-utilities scaffolding tables thumbnails tooltip type utilities utility wells; do
	echo Compiling $file
	sass --sourcemap=none --style=compressed scss/bootstrap/$file.scss css/bootstrap/bootstrap-$file.min.css
	sass --sourcemap=none --style=expanded scss/bootstrap/$file.scss scss/bootstrap/css/bootstrap-$file.css
done
echo Compiling main bootstrap file
sass --sourcemap=none --style=compressed scss/bootstrap/bootstrap.scss css/bootstrap.min.css
